from dataclasses import dataclass
from enum import Enum, auto
from datetime import datetime
from typing import Optional

class SignalType(Enum):
    LONG = auto()
    SHORT = auto()
    EXIT = auto()

class OrderType(Enum):
    MARKET = auto()
    LIMIT = auto()
    STOP = auto()
    CANCEL_ALL = auto()

class OrderSide(Enum):
    BUY = auto()
    SELL = auto()

class OrderStatus(Enum):
    CREATED = auto()
    SUBMITTED = auto()
    PARTIAL = auto()
    FILLED = auto()
    CANCELED = auto()
    REJECTED = auto()

@dataclass(frozen=True)
class Instrument:
    """Defines the specifications of a tradable asset."""
    symbol: str
    multiplier: float = 1.0
    tick_size: float = 0.01
    margin_req: float = 0.0

@dataclass(frozen=True)
class Bar:
    """Represents a single OHLCV bar for a symbol."""
    symbol: str
    timestamp: datetime
    open: float
    high: float
    low: float
    close: float
    volume: float

@dataclass(frozen=True)
class SignalEvent:
    """Generated by the Strategy, consumed by the Portfolio."""
    symbol: str
    timestamp: datetime
    signal_type: SignalType
    target_price: Optional[float] = None  # For Limit/Stop orders
    target_qty: Optional[int] = None      # Optional: direct quantity request
    strength: float = 1.0                 # 0.0 to 1.0, confidence factor

@dataclass
class OrderEvent:
    """Generated by the Portfolio, consumed by the ExecutionHandler."""
    symbol: str
    timestamp: datetime
    quantity: int         # Positive for BUY, Negative for SELL? Or use Side?
    side: OrderSide       # Explicit side is usually safer
    order_type: OrderType
    limit_price: Optional[float] = None
    stop_price: Optional[float] = None
    status: OrderStatus = OrderStatus.CREATED

@dataclass(frozen=True)
class FillEvent:
    """Generated by the ExecutionHandler, consumed by the Portfolio."""
    symbol: str
    timestamp: datetime
    quantity: int
    price: float
    commission: float
    slippage: float
    side: OrderSide
    exchange_id: Optional[str] = None
